### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by rakshitmidha** [MrToph/react-d3-bubblechart#1]
Module not found: 'child_process' in react-d3-bubblechart/node_modules/xmlhttprequest/lib
@ ./~/xmlhttprequest/lib/XMLHttpRequest.js 15:12-36

**Comment by MrToph** [comment]
I don't have any dependency on `xmlhttprequest`. Not sure where this is coming from.

Maybe it's a dependency of a dependency that changed in some update. Try installing the exact versions specified in `package.json`

**Comment by unkleho** [comment]
Changing d3 from "^4.4.3" to "4.4.3" did the trick for me.
