### ISSUE TITLE
Is it possible to use react: ^16.1.1 with d3 ^4.12.2

### ISSUE THREAD

**Issue by archi0309** [MrToph/react-d3-bubblechart#2]
I am stuck in old react validation package.

Uncaught TypeError: Cannot read property 'number' of undefined

ChartTitle.propTypes = {                                                                                               // 70
  width: _react.PropTypes.number.isRequired,                                                                           // 71
  title: _react.PropTypes.string,                                                                                      // 72
  titleClassName: _react.PropTypes.string                                                                              // 73
};

**Comment by MrToph** [comment]
Sure, feel free to create a PR and update React and PropTypes everywhere it's used.
